import com.blamejared.gradle.mod.utils.GMUtils
import com.blamejared.gradle.mod.utils.values.GitChangelogValue
plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id "com.modrinth.minotaur" version "2.+"
    id "com.blamejared.gradle-mod-utils" version "1.0.5"
}

base {
    archivesName = "${mod_name}-fabric-${minecraft_version}"
}
version = GMUtils.updatingVersion(version as String)
apply from: 'gradle/property_loader.gradle'
apply from: 'gradle/git_changelog.gradle'

repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId base.archivesName.get()
            version project.version
            from components.java
        }
    }

    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}

task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {

    description = 'Publishes the build to CurseForge.'

    apiToken = System.getenv("CURSEFORGE_API_TOKEN")

    def mainFile = upload(575305, file("${project.buildDir}/libs/${base.archivesName.get()}-${version}.jar"))
    mainFile.changelog = project.ext.mod_changelog
    mainFile.releaseType = 'release'
    mainFile.changelogType = 'markdown'
    def sourcesFile = mainFile.withAdditionalFile(sourcesJar)
    def javadocFile = mainFile.withAdditionalFile(javadocJar)
}

modrinth {
    token.set(GMUtils.locateProperty(project, 'MODRINTH_API_TOKEN'))
    projectId.set("E7ZFR7qk")
    changelog.set(providers.of(GitChangelogValue) {
        parameters.repository.set(mod_source)
    }.get())
    versionName.set("Fabric-${minecraft_version}-$version")
    versionType.set('release')
    gameVersions.set([minecraft_version])
    uploadFile.set(tasks.jar)
    dependencies {
        required.project('fabric-api')
    }
}
tasks.modrinth.dependsOn(tasks.jar)
